### ISSUE TITLE
All Random Element Selection

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#128]
I got Water 2 at wave 5. Water 3 at wave 20. Both are too early.

**Comment by WindStrike72** [comment]
Earliest you should be able to get a Level 2 element for Random is what, Wave 10 (3rd element pick) and Wave 35 (7th element pick), I believe. For express, should be Wave 6 (4th element pick) and Wave 15 (7th element pick), unless we wanna change that to match Classic mode's 3rd and 7th.

**Comment by MNoya** [comment]
[this code](https://github.com/Karawasa/Element-TD/blob/master/game/dota_addons/element_td/scripts/vscripts/gamesettings.lua#L169-L203) controls the random rules, the restrictions are there **but** it's currently not tied to each player ID (all usedElements are compared towards a single table for everyone) so that's the most likely problem. I will review it tomorrow, I've never encountered this problem before except this time where we both enabled -random after All Pick was voted (old AllRandom option was nuked, so it makes sense that it's malfunctioning)
