### ISSUE TITLE
Statcollection

### ISSUE THREAD

**Issue by ynohtna92** [Karawasa/Element-TD#14]
@Karawasa Will we be using stat collection to collect game stats? http://getdotastats.com/#s2__directory

**Comment by MNoya** [comment]
Why wouldn't we? At least to begin with, get an idea of gameplays and building a schema to keep track of tower/element usage

For scores and highscores though, we need to build something else

**Comment by ynohtna92** [comment]
Just wondering so that we can get started on building the schema required for it.
In which case what will we be logging?

**Comment by MNoya** [comment]
Apart from the obvious scores/wave reached, I can think of the following endgame stats to track:
- All 6 element levels
- Element build order (only when each lvl 1 element gets acquired, not past that)
  - Can be done as 6 separate entries if its faster/easier to keep track of it this way
- Lumber used
- Essence used
- Lives gained (from life tower), lives lost
- Interest gold earned, gold tower earned, networth
- Num of towers built and sold
- Gold loss from selling
- Final num of towers, with element breakdown

**Comment by Karawasa** [comment]
Nice start on possible stats to collect. Why limit element build order to lvl 1? Higher levels impact the build just as much?

**Comment by MNoya** [comment]
I thought only tracking lvl 1 because if there's more than 6 variables, it makes it very hard to get any meaningful data from pie charts: http://getdotastats.com/#s2__mod_cpv?id=96

If the entry is a single line (a string `DLEN` for example) there could be up to thousand of possible combinations. If that's expanded to send `DLLEEDLDNNN` and beyond, it makes up for realistically million of combinations, so I think there would be no way of telling "This build is popular, this build isn't"

A more meaningful way to get popularity build from one single entry would be combinations without repetition, possible entries are 6 (purely 1 element used) + 15 (duals) + 20 (triples) + 15 (four elements used) + 6 (five elements) + 1 (all used). That gives us 63 possible values, and can certainly say "D+L+E is more popular than F+W+N"

**Comment by jimmydorry** [comment]
Wouldn't it be easier to just collect how many levels of each element each player got at the end of the game?

I thought complete build orders were a great idea, but after seeing them on a few mods... they only make sense when you have a huge number of games played. Enough to get meaningful data for all the combos.

If you want to be balancing on build orders, tracking via separate variables seems to be the way to go (variable for first element, variable for second, etc.). 

I doubt you would want to track a build order greater than 5 or so to start with, as I bet most players won't get that far into the game).

Tracking what elemental combos used is a pretty neat idea though, so you could also add separate variables for combos built (but only populated when they build a tower of that combo). Like combo1: LE, combo2: DL, etc. You again probably won't be interested in tracking more than the first 5 to start with.

I'm happy enough to see you guys experiment by throwing a whole heap of schemas out there, and seeing what sticks.

**Comment by MNoya** [comment]
> Wouldn't it be easier to just collect how many levels of each element each player got at the end of the game?

Yeah that was covered by 'All 6 element levels'

> [build orders] ... they only make sense when you have a huge number of games played

We hope to get there with this gamemode, its likely! That's why I think build orders could be of some use. Maybe we could track up the first 5~6 element acquired used in separate variables (to get an idea of which elems are more popular early), but I think combinations without repetition or order (63 possible builds) could work after a thousand games, and it's just a 6 letter string

**Comment by Karawasa** [comment]
I appreciate the discussion. But I feel strongly about collecting the entire build order (11 picks). This data will be invaluable for long term balancing.

As for number of games, you guys are underestimating the potential. We will have a huge number of games. Gem TD has ~800,000 subscriptions...we are going to smash that.

**Comment by jimmydorry** [comment]
As counter point, Dota Imba has 2,555,213 subscribers right now and about 60,000 games a week. 

It has enough data to put about 5,000 data points on each of the 100 or so heroes... but if you are talking about a build order of 6 options, that is like 362,797,056 combinations... there may be some builds with 100 usages... but the majority are going to have a single play.

**Comment by jimmydorry** [comment]
I think I explained my idea for your schema poorly. This is what I was thinking of as a guide (don't really mind what you go with, as long as it's sane):

---
- **Name** -- **Value** -- **Comment**
- Light -- 1 -- levels in light
- Dark -- 2 -- levels in dark
- Water -- 1 -- levels in water
- etc.

---
- ele1 -- dark -- the first element levelled up
- ele2 -- light -- the second element levelled up
- ele3 -- water -- the third element levelled up
- ele4 -- dark -- the fourth element levelled up
- etc. (you probably don't want to track more than 10 to begin with, but this easily changed later)

---
- combo1 -- DL -- the first unique tower combo built
- combo2 -- LW -- the second unique tower combo built
- combo3 -- DLW -- the third unique tower combo built
- combo4 -- DW -- the fourth unique tower combo built
- etc. (you probably don't want to track more than 5 to begin with, but this easily changed later)

---

The advantage of the above, is that you get nice piecharts and can easily compare win-rates across players, no matter how far they got into the game.

**Comment by MNoya** [comment]
Sounds much better than what I had in mind!

**Comment by MNoya** [comment]
Current schema proposal: https://github.com/Karawasa/ElementTD/blob/master/game/dota_addons/element_td/scripts/vscripts/statcollection/schema.lua#L63-L106

It looks like this: http://www.hastebin.com/kajalaguko.coffee

I made a "DE" "DEN" style of string, I can do the same for full element strings like "light"
