### ISSUE TITLE
Investigate loading crash

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#164]
I got a report that after the loadscreen goes away and players are spawned ingame, the game crashes for some people (most likely shit pcs) at the same very moment, consistently.

**Comment by MNoya** [comment]
> Elklopso: I just got in a 6 player one
> Elklopso: instant dc

**Comment by elklopso** [comment]
Its not even a shit PC :) Its an i5 4430 with 8gb ram and a R9 2xx. And when I started a solo game it all went smooth.

**Comment by IPROJECT-7** [comment]
Its not just you mate, me and some of my friends are facing the same issue, i have a lenovo i5 5th gen 4gb ram so i doubt specs are the issue here, there is probably a memory related problem on the back end, as after timeout if i recon game is smooth, it just takes too much memory the moment all players load.

**Comment by MNoya** [comment]
Let's see if this 40be386065f5c1d6c3f7703ccda6481399201b86 fixes it

**Comment by MNoya** [comment]
A 2nd run crash: http://pastebin.com/6Hi5Fzbu

See the last line:

```
***** OUT OF MEMORY! /+/ attempted allocation size: 45849600 ****
```

Need to forward this to Valve.

**Comment by IPROJECT-7** [comment]
Link dosent work.

**Comment by MNoya** [comment]
Seems to have been fixed after the last patch reduced precache & loading screen size.

Comment/Reopen if it happens again.
