### ISSUE TITLE
In-game ranking not updating

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#457]
http://forums.eletd.com/topic/95700-classic-frog-rank/

No idea if it's something on our end or another one of those "thanks Volvo".

**Comment by ynohtna92** [comment]
It is because the website versions are not dynamic and they need to be updated on the site for it display correctly manually.

**Comment by ynohtna92** [comment]
I'm going to attempt to make a script for you that you can use to update this manually more easily.

**Comment by ynohtna92** [comment]
@WindStrike72 You know what, just ping me when you update the game version and i'll do it for hatinacat.com, who is updating it on eletd.com?

**Comment by biax** [comment]
Can I have the webapp & sql files? I can throw a copy to a container in 
one of my VPS, learn how to do updates upon each version update and do 
future maintenance on it as well as add features.

**Comment by MNoya** [comment]
while we are at it, we also need to update the [ip whitelist](https://github.com/MNoya/Element-TD/blob/dev/game/dota_addons/element_td/scripts/IP_WhiteList.txt)

**Comment by biax** [comment]
I believe this was already updated in in one of the recent commits

**Comment by MNoya** [comment]
The files on this repo aren't automatically pushed to the server

**Comment by ynohtna92** [comment]
@biax here is the cloned repo. The app should be the same as what is on hatinacat.com minus the database since it is huge. However there is a sample database there to use (I'm not sure if it has all the columns though so you will need to compare it to the model).

https://www.dropbox.com/s/7alnxmuq1t4a7m2/ElementTDLeaderboard.zip?dl=0

I have also added you as a collaborator to the private repo, please work on your own branch however and I'll approve mergers.

@MNoya the hatinacat.com app has been updated with that ip whitelist.
