### ISSUE TITLE
The state of quake tower

### ISSUE THREAD

**Issue by biax** [Karawasa/Element-TD#478]
Eventually this tower will become the new meta and when that happens, here are some options:

1. Have more %-based towers?
2. Allow %-damage on level2 quake onwards or maybe even level3 but reduce damage to 0%/1%/2% ? I lean towards % on quake2 onwards. I'm sure some certain players will spam it but we shouldn't be seeing 30 of these towers built all over.
3. Remove % all together?

I like option 2 the most.. but by doing so, I think its fair if all towers receive changes of similar format.

**Comment by WindStrike72** [comment]
I vote option 1, it allows for all towers to stay relevant throughout the whole game, even if their damage falls off. Plus, I think it's actually cool that builds w/ just 1 into the element are cropping up, instead of all high level stuff only. Rather than go for 0% of the new effect @ level 1, just keep it really low of whatever it is (ie, **Level 1 Ice Tower** causes a decent effect even later on, but its form is fairly limited).

Nutshell, just add more minor support abilities to all the towers that don't already have them. Stuff like single-target stacking slows, stacking damage amps, maybe even ability silences, etc. Doesn't have to be all this patch, this is the sort of thing we could get away with just tweaking a few towers per patch, until all towers have said minor support abilities.

Just mah two cents on it.

**Comment by Karawasa** [comment]
This is all wrong. You mean Karawasa tower right?
