### ISSUE TITLE
Dota 7.00 Patch

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#479]
As you might know by now, a huge dota patch was just released in test client yesterday and it's meant to hit the main client by today.

It's UI changes will most likely make the game very awkward if not unplayable. I'm not sure if we'll have ability/mechanic issues but it's likely.

Please report any problem caused by the patch under the 'Dota 7.00' milestone, My free time between work and december exams but I'll try to assist and fix everything that breakes the game.

**Comment by biax** [comment]
If you're going to make UI changes, would it consume too much of your 
time to include the statistics feature (during terrain-selection phase) 
I mentioned earlier?

I can draw a full proper mockup very quickly if you can do so. I believe 
this is a little out of my capability.

**Comment by MNoya** [comment]
Releasing a patch full of bug fixes asap should be the priority.

You can include the the stats feature mockup on #477 and I'll take a look at it after we close the critical issues first :smiley:

**Comment by WindStrike72** [comment]
Visual bugs:
- [Looks a little bland here](http://prnt.sc/diyu34)
- [Bottom Left & Bottom Right corners gave up a bit](http://prnt.sc/diyurz)
- [Top bar backdrop went bye-bye](http://prnt.sc/diyuxl)
- When selecting to build and place a tower, they look a bit... [stripped](http://prnt.sc/diyvr3)

Performance bugs:
- Building a tower I haven't built before in this patch is crashing the game for me in main client. Haven't checked tools mode yet. Though, once I actually build the tower once, I'm good.

**Comment by WindStrike72** [comment]
Summoning center hotkey appears to have gone borked as well.

**Comment by ynohtna92** [comment]
Why is the map outside of the map box?

I will reduce the height of the player slots to make it fit better on the top bar. We should also put boxes around the bottom right stuff.

All the changes will so need to be tested on 3:4, 16:9, 16:10, 21:9

**Comment by biax** [comment]
![screenshot_71](https://cloud.githubusercontent.com/assets/15166474/21156649/92944fce-c1b1-11e6-81ab-ed9f51e78a52.png)

heres my input on tidying the UI while you're at it. @WindStrike72 do review

**Comment by WindStrike72** [comment]
Another bug:
- So I've got 4 lumber, and I've got my builder selected, but because there's no generic "select upgrade" icon, I can't level my elements from here. [See here](http://prnt.sc/dj266r)
- Though, that begs a bit of a question. With the new leveling UI just sticking '+' signs over all the abilities, would it be easier to actually nuke the lumber resource, nuke the elemental summoner, and instead just go with leveling up the hero every 5 waves (3 on express)? So if you started on Express mode, you'd start as Level 2, and if you're on Short mode, you'd start as Level 4. Though I suppose there's no button for random or gaining more essences... I dunno, go with whatever fix is more convenient fer ya **Noya**.

Regarding UI cleanup no jutsu from **biax**:
- Yeah, I'd second removing the elements counter in the bottom-right, it's even more obvious now w/ the new UI. Especially if we wanna fit the new natural UI size in the bottom-right. [See here for reference](http://prnt.sc/dj245h)
- If anything, stick score under the wave box in the top-right, because right under that is where the score bonuses plop up each wave and at the end of the game.
- Now that there's space, could we move the Settings Icon to the left of the bottom-right area, instead of above? Keep the size as is, it should be fine like that. I've often found myself clicking on it by accident instead of a tower around that area of the screen.
- I have no frigin' clue where the heck the Tower Table icon should be now, cause I'm pretty sure it's now covering where the new UI backdrop there would be. Not unless we're doin' a custom backdrop, in which case go nuts.

FYI, mah suggestions are intended as mainly a "if it's no real trouble compared to just fixing it".


Also, the screenshot I posted was in 16:9. I'll poke the Karawasanator to check out 21:9 and post a screenshot of how borked it is once fixes are applied. Dunno anyone w/ 4:3 or 16:10 though.

**Comment by ynohtna92** [comment]
You can scale to 21:9 yourself if you set the width and height to the values I have commented in that .lua file.

**Comment by biax** [comment]
Is nobody updating eletd for 7.00? There are 1200 people playing it 
right now strangely. Ranked 4

**Comment by WindStrike72** [comment]
Game of the day happened, though I'm surprised it jumped up that high, given there's multiple bug reports of people not being able to select elements, though I didn't get the issue on my end.

If Noya/Quint/etc. are willing to fix it, let's keep it to the bare minimum and just fix what's broken, not get all the other requested changes. I think there's still some backlog of balance changes that were applied already, so I can get the tooltips with them, don't think it was a whole lot of changes.

**Comment by Karawasa** [comment]
@biax Are you able to contribute? Currently, no one is working on updating for 7.00. Any and all help would be appreciated. I agree with @WindStrike72 that we should do the bare minimum.

**Comment by biax** [comment]
To do that, I will first need to know how to do it.. which neither me or 
wind knows

**Comment by ynohtna92** [comment]
I just got back from being interstate so I can probably get started on some of the fixes. I just need clear reproducible bug reports to do things quickly. I'll tackle the game breaking issues first. Is there a priority list I could follow?

**Comment by Karawasa** [comment]
@ynohtna92 That is really great news! I'm not sure about a priority list. @WindStrike72 can you help with that?

**Comment by WindStrike72** [comment]
I'll look into it, starting with the game breaking bugs list. Not sure if I can reproduce them, I recall trying some of them out, and it never crashed on my end. Might've been specific dota versions that were causing it. We'll see. I'll try to get this up in the next day.

**Comment by biax** [comment]
i'll list whatever issues i can find, of whatever priority:

in-game interface -- refer to: https://github.com/MNoya/Element-TD/issues/479#issuecomment-266844811

cosmetics issue:
![screenshot_89](https://cloud.githubusercontent.com/assets/15166474/22227250/5a4c6d08-e205-11e6-9e74-c7ade00997ca.png)

reproducible crash (tested on my pc only so far, ill wait for some pals to help me test this later): start game -> sandbox -> pause and wait results in dota2 crashing. might need to scroll around a bit im not sure.

**Comment by WindStrike72** [comment]
I'm not running into any crash errors personally anymore, buuut that doesn't mean they're not there.

In terms of visual bugs, I think they're all outlined above and are all still valid. Just do whatever fixes for those that's fastest, no need to do anything fancy.

I just ran a test of all the towers; functionally, they're all still perfectly fine, no visual bugs on them (I think), only thing that was out-of-place was having a pure dark w/ level 3 forge buff and its damage numbers almost going all the way across the portrait, which is hilarious, but hey, at least you can properly see buffed damage numbers now.

For priority list, check out the talent tree crash error and goat's sandbox error, and then after that, look into the visual bugs, which to my knowledge is mainly a bunch of floating UI stuff with missing backdrops.

**Comment by ynohtna92** [comment]
https://github.com/MNoya/Element-TD/commit/e385f559868d0ef876c19b9b2c9d6b72c4c76bc7 Removed 700 UI additions and fixed the left side of the screen.

**Comment by ynohtna92** [comment]
https://github.com/MNoya/Element-TD/commit/e43998cda2813ba1d6ecdb38a2229fe41a78ad4e Fixed top bar button layout.

**Comment by ynohtna92** [comment]
I haven't been able to replicate any crashes or being unable to upgrade elements as the game is played. Can you provide more insight into this mechanic breaking?

**Comment by biax** [comment]
did you try sandbox + pause? i had crashes there (havent tested latest 
commits though)

**Comment by Karawasa** [comment]
I know this is low priority but I would actually like to play this again...so please fix ultra-wide resolution! I can post a screenshot of how it looks to me when I get home.

**Comment by MNoya** [comment]
you can play in windowed mode for the time being :sweat_smile:

**Comment by Karawasa** [comment]
:(

**Comment by ynohtna92** [comment]
https://github.com/MNoya/Element-TD/commit/bc6c86c800660e137777f7a4199648ce7bc78914 Fixes the layout for 21x9

@biax Yes I have tried and it works fine.  It could be a dedicated server issue that I cannot reproduce.

I have noticed that onmouseover no longer is working for wave_info.xml. And I have no idea how to fix it.
Our element level up panel also no longer exist.

You should be able to test and push these changes to the master for now so people stop complaining @WindStrike72. I will update the leaderboard tables as well so the correct ones are displaying.

**Comment by WindStrike72** [comment]
I'm going ahead and pushing latest changes to public client since it fixes the talent tree crash error and few other UI things, though know I'm intending on running a follow-up patch w/ the actual changelog, tooltips, and remaining fixes you guys are working on. Thanks for taking the time to try and fix el broken doto!

**Comment by Karawasa** [comment]
Yes thank you guys!

**Comment by MNoya** [comment]
Alright if any other problem appears let's make a separate issue, game seems stable now.
