### ISSUE TITLE
Pure Essence Random Pick Gold Bonus

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#93]
In our last game (where I got stomped), @WindStrike72 randomed a pure essence but did not get any gold.

**Comment by MNoya** [comment]
Disabling pure randoming might be the best option

**Comment by Karawasa** [comment]
Hmm. Why?

**Comment by MNoya** [comment]
> WindStrike: more times than not, I got screwed over in random games by pure essences
> WindStrike: that gold bonus doesn't actually help that much unless you get it in mid-game so the interest racks up a bunch
> WindStrike: usually, it'd give it as a last pick, and it any other element would've helped more

Maybe if the gold bonus was big enough, what is the formula supposed to be?

**Comment by WindStrike72** [comment]
Original formula in SC2 version was 2.5 \* (Wave ^2). Translated to dota, because the first 5 waves are cut out, it's 2.5 \* [(Wave +5) ^2]. What SC2 didn't have was something that accounted for bounty modifier for difficulty, and since I usually played on Very Hard or Insane... said gold bonus was a little underwhelming. With the current formula of 2.5 \* [(Wave +5) ^2] \* Difficulty Modifier... it may work out fine in random afterall.
